class EXc{ 
	public static void main(String[] args){
/*		try{
			
		}catch(ArithmeticException ae){
		}catch(NullPointerException ne){
		}catch(ArithmeticException a){}  //error  exception ArithmeticException has already been caught
*/

/*		try{
		}catch(Exception e){
			
		}catch(ArithmeticException a){   //exception ArithmeticException has already been caught
*/
		
		try{                          
		}catch(ArithmeticException e){          
			                          
		}catch(Exception a){    //allowe beacause I understood first child then last parent.

		}
	}
}

